from pathlib import Path

from isbe.memory.loader import EXCLUDED_DIRS, load_index

ARCHIVE_DIR = ".archive"


def reindex_memory_md(memory_root: Path) -> None:
    """Rewrite memory_root/MEMORY.md from current in-tree files.

    Excludes .pending, .audit, .archive directories.
    Active reading entries (not archived) are included.
    """
    entries = load_index(memory_root)
    # extra exclusion: .archive (load_index already excludes .pending/.audit)
    entries = [e for e in entries if ARCHIVE_DIR not in e.path.parts]
    lines = ["# MEMORY index (auto-generated by lifecycle.reindex_memory_md)\n", ""]
    for e in sorted(entries, key=lambda x: str(x.path)):
        rel = e.path.relative_to(memory_root).as_posix()
        lines.append(f"- [{e.frontmatter.name}]({rel}) — {e.frontmatter.description}")
    (memory_root / "MEMORY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
